# Generated by Django 4.2.2 on 2023-06-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concesion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo_de_concesion', models.CharField()),
                ('comuna', models.CharField()),
                ('lugar', models.CharField()),
                ('n_rs_ds', models.CharField()),
                ('tipo_tramite', models.CharField()),
                ('concesionario', models.CharField()),
                ('tipo_vigencia', models.CharField()),
            ],
        ),
    ]
