# Generated by Django 4.2.2 on 2023-06-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarea_1_app', '0002_alter_valoresjurisprudencia_jurisprudencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoresjurisprudencia',
            name='idItemlista',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='valoresjurisprudencia',
            name='jurisprudencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarea_1_app.jurisprudencia'),
        ),
    ]
