# Generated by Django 4.2.2 on 2023-06-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea_1_app', '0003_alter_valoresjurisprudencia_iditemlista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoresjurisprudencia',
            name='idItemlista',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
